blank_issues_enabled: false
contact_links:
  - name: Documentation Issue
    url: https://github.com/apache/pulsar-site/issues/new
    about: Please report documentation issues at the Apache Pulsar site repository
